# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff6dcb16929e4ee32fadf92b952451e5cb9c3436925d4f3fad6b728676baa3252a4f2766e08bd5cf6f559de3d5ffb549c9b65c5ea2ea333f187d094a939f7b01

test:
  secret_key_base: d900f6b59e4d1360b6095050cae868c595afda094f5ca450f556336b143f9f2e5cdd0b4a401fb6f25122b1e960d83140b2b8f4c30b3feed64b35a22c049998c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
